[package]
name = "nyan_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.4"
actix-rt = "2.3"
actix-web = "4"
reqwest = "0.11"
regex = "1.5"
pkg-config = "0.3.27"
